"use client";

import Link from "next/link";
import { useEffect, useRef } from "react";
import FounderPortrait from "@/components/portfolio/FounderPortrait";
import PublicFrame, { Arrow } from "@/components/portfolio/PublicFrame";

const newsletterUrl =
  "https://9d400ade.sibforms.com/serve/MUIFAPExZZx-JCjXBLd6WTYMm8vRj63zvNsbCmkq-1mjrjOv9k_JWEyebEiyItVE_L4EyZ5Xfqn7ErmdwXwYD9Y3SSp1AZpfFY-SMJPjZI2kMDyS7fxtSfotCUyqAufENqxrzITGc-4DKo2hnCJzIFoeLQXtiRaVxjRRA8wNfJHFSKzviHtk067OjA1clW2c4zDXUsRvGTg7jYcFpg==";

const services = [
  {
    id: "cybersecurity-audit",
    index: "01",
    title: "Cybersecurity Audit",
    summary: "A full read on where your organization actually stands.",
    detail:
      "I review your accounts, devices, access rules and day-to-day habits, then tell you plainly what is exposed and what is fine. No scare tactics, no 80-page report nobody opens.",
    deliverables: [
      "Access and account review",
      "Device and network posture",
      "Written findings, ranked by risk",
    ],
  },
  {
    id: "penetration-testing",
    index: "02",
    title: "Penetration Testing",
    summary:
      "Controlled, authorized attempts to get in — before someone uninvited tries.",
    detail:
      "Scope is agreed in writing first. I work the way an attacker would, document every step, and show you exactly which door opened and why it opened.",
    deliverables: [
      "Agreed scope and rules of engagement",
      "Reproducible attack paths",
      "Fix guidance your team can action",
    ],
  },
  {
    id: "website-vulnerability-detection",
    index: "03",
    title: "Website Vulnerability Detection",
    summary:
      "For the site your customers, patients or clients trust with their data.",
    detail:
      "Forms, logins, payments, plugins and configuration get checked for the flaws that are actually used in the wild. You get a short list of what to fix, in order.",
    deliverables: [
      "Form, login and payment path testing",
      "Dependency and configuration checks",
      "Prioritized remediation list",
    ],
  },
];

const approach = [
  {
    index: "01",
    title: "Define the scope",
    body: "We agree on what is in bounds, what is off limits, and what a good outcome looks like. Everything is in writing before any testing begins.",
  },
  {
    index: "02",
    title: "Validate the findings",
    body: "Nothing goes in a report until I can reproduce it. You will not get a list of maybes generated by a scanner — you get confirmed issues with evidence.",
  },
  {
    index: "03",
    title: "Make the next move clear",
    body: "Findings are ranked by real risk to your operation, with the fix spelled out in language your team can act on this week.",
  },
];

export default function FounderLinkHubClient() {
  const mainRef = useRef<HTMLElement>(null);
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("in-view");
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.12 },
    );
    mainRef.current
      ?.querySelectorAll("[data-reveal]")
      .forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  return (
    <PublicFrame>
      <main id="main" ref={mainRef}>
        <section className="portfolio-hero" aria-labelledby="hero-title">
          <div className="hero-copy">
            <p className="technical-label hero-intro">
              Discipline <span aria-hidden="true">·</span> Curiosity{" "}
              <span aria-hidden="true">·</span> Purpose
            </p>
            <h1 id="hero-title">
              A life of service.
              <br />
              <em>A new front line.</em>
            </h1>
            <p className="hero-description">
              Marine veteran. Former Special Operations interpreter in Iraq. Now
              a cybersecurity student doing the same work in different terrain —
              finding what is exposed before someone else does.
            </p>
            <div className="hero-actions">
              <Link href="/review" className="portfolio-button solid">
                Request a security review <Arrow />
              </Link>
              <p className="technical-label hero-subline">
                Independent · Scope agreed in writing
              </p>
            </div>
          </div>
          <FounderPortrait />
        </section>

        <section id="story" className="story-section chapter-section">
          <div className="chapter-split">
            <div className="chapter-heading">
              <span className="technical-label">01 / The foundation</span>
            </div>
            <div className="story-copy" data-reveal>
              <h2>
                Different terrain.{" "}
                <em>The same responsibility.</em>
              </h2>
              <p>
                I spent years as a Marine, and before that as a Special
                Operations interpreter in Iraq. The job was to understand the
                ground, understand the people on it, and give the team an honest
                picture — including the parts nobody wanted to hear.
              </p>
              <p>
                Cybersecurity asks for the same thing. Most organizations are
                not breached by something exotic. They are breached through an
                account nobody closed, a plugin nobody updated, a process
                everybody assumed someone else owned.
              </p>
              <p className="story-emphasis">
                My work is to look at your systems the way I looked at terrain:
                carefully, without flattery, and with a clear recommendation at
                the end.
              </p>
              <div className="story-signature">
                <span>Azad Sleigher</span>
                <span className="technical-label">Founder, Cyber Ethos</span>
              </div>
            </div>
          </div>
        </section>

        <section id="services" className="services-section chapter-section">
          <div className="chapter-split">
            <div className="chapter-heading">
              <span className="technical-label">02 / The work</span>
            </div>
            <div className="section-introduction" data-reveal>
              <h2>Three ways I can help</h2>
              <p>
                Most engagements start with an audit and go from there. If you
                already know what you are worried about, say so and we will
                scope only that.
              </p>
            </div>
          </div>
          <div className="service-list">
            {services.map((service) => (
              <article className="service-article" key={service.id} data-reveal>
                <div className="service-lead">
                  <p className="technical-label">{service.index}</p>
                  <h3>{service.title}</h3>
                  <p className="service-summary">{service.summary}</p>
                </div>
                <div className="service-detail">
                  <p>{service.detail}</p>
                  <Link
                    href={`/review?service=${service.id}`}
                    className="service-scope"
                  >
                    Scope this engagement <Arrow />
                  </Link>
                </div>
                <ul className="service-deliverables">
                  {service.deliverables.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              </article>
            ))}
          </div>
          <p className="scope-note">
            Testing only with explicit authorization and agreed scope. No
            credentials or sensitive data in your first message.
          </p>
        </section>

        <section id="approach" className="approach-section chapter-section">
          <div className="chapter-split">
            <div className="chapter-heading">
              <span className="technical-label">03 / The method</span>
            </div>
            <h2 data-reveal>
              How an engagement <em>actually runs</em>
            </h2>
          </div>
          <ol className="approach-grid">
            {approach.map((step) => (
              <li key={step.index} data-reveal>
                <span className="technical-label">{step.index}</span>
                <h3>{step.title}</h3>
                <p>{step.body}</p>
              </li>
            ))}
          </ol>
        </section>

        <section id="contact" className="contact-section chapter-section">
          <div className="chapter-split">
            <div className="chapter-heading">
              <span className="technical-label">04 / The conversation</span>
            </div>
            <div data-reveal>
              <h2>
                What needs a <em>closer look?</em>
              </h2>
              <p>
                Tell me what you run and what keeps you up at night. I will tell
                you honestly whether you need a review, a test, or nothing at
                all right now.
              </p>
              <div className="hero-actions">
                <Link href="/review" className="portfolio-button solid">
                  Request a security review <Arrow />
                </Link>
                <a className="contact-email" href="mailto:info@cyberethos.org">
                  info@cyberethos.org <Arrow />
                </a>
              </div>
            </div>
          </div>
        </section>

        <section
          id="newsletter"
          className="newsletter-section chapter-section"
          aria-labelledby="newsletter-title"
        >
          <div className="chapter-split newsletter-intro">
            <div className="chapter-heading">
              <h2 id="newsletter-title" className="technical-label">
                05 / The newsletter
              </h2>
            </div>
            <div>
              <p className="newsletter-heading">
                Plain notes on staying secure
              </p>
              <p className="newsletter-copy">
                Occasional, short, no product pitches. What I am seeing and what
                I would fix first.
              </p>
            </div>
          </div>
          {/* Brevo owns the signup copy, consent, and confirmation UI. */}
          <iframe
            className="newsletter-frame"
            src={newsletterUrl}
            title="Subscribe to the Cyber Ethos security newsletter"
            loading="lazy"
            width="640"
            height="620"
          />
          <p className="newsletter-fallback">
            Form not loading?{" "}
            <a href={newsletterUrl} target="_blank" rel="noopener noreferrer">
              Open the signup form in a new tab <Arrow diagonal />
            </a>
          </p>
        </section>
      </main>
    </PublicFrame>
  );
}
